#pragma once
#include <array>
#include <string_view>

namespace example
{
    using namespace std::string_view_literals;
    [[maybe_unused]] static constexpr std::array rules1{
        "light red bags contain 1 bright white bag, 2 muted yellow bags."sv,
        "dark orange bags contain 3 bright white bags, 4 muted yellow bags."sv,
        "bright white bags contain 1 shiny gold bag."sv,
        "muted yellow bags contain 2 shiny gold bags, 9 faded blue bags."sv,
        "shiny gold bags contain 1 dark olive bag, 2 vibrant plum bags."sv,
        "dark olive bags contain 3 faded blue bags, 4 dotted black bags."sv,
        "vibrant plum bags contain 5 faded blue bags, 6 dotted black bags."sv,
        "faded blue bags contain no other bags."sv,
        "dotted black bags contain no other bags."sv,
    };

    [[maybe_unused]] static constexpr std::array rules2{
        "shiny gold bags contain 2 dark red bags."sv,
        "dark red bags contain 2 dark orange bags."sv,
        "dark orange bags contain 2 dark yellow bags."sv,
        "dark yellow bags contain 2 dark green bags."sv,
        "dark green bags contain 2 dark blue bags."sv,
        "dark blue bags contain 2 dark violet bags."sv,
        "dark violet bags contain no other bags."sv,
    };
}

namespace input
{
    using namespace std::string_view_literals;
    static constexpr auto mybag = "shiny gold"sv;

    static constexpr std::array rules{
        "pale turquoise bags contain 3 muted cyan bags, 5 striped teal bags."sv,
        "light tan bags contain 5 posh tomato bags."sv,
        "shiny coral bags contain 2 muted bronze bags."sv,
        "wavy orange bags contain 4 faded tomato bags."sv,
        "light plum bags contain 3 drab orange bags, 4 faded coral bags."sv,
        "pale purple bags contain 5 bright crimson bags."sv,
        "bright blue bags contain 1 pale beige bag, 1 light teal bag."sv,
        "pale bronze bags contain 1 dotted salmon bag, 1 striped blue bag, 2 clear tan bags."sv,
        "muted maroon bags contain 5 pale crimson bags."sv,
        "clear lavender bags contain 4 vibrant black bags, 2 posh red bags."sv,
        "pale cyan bags contain 4 light olive bags, 2 dull lime bags, 4 faded black bags, 4 plaid red bags."sv,
        "faded blue bags contain 1 posh tan bag, 1 dotted violet bag, 3 posh gold bags."sv,
        "wavy teal bags contain 3 pale brown bags."sv,
        "striped red bags contain 2 light bronze bags, 3 dark cyan bags."sv,
        "drab brown bags contain 3 striped magenta bags, 3 clear silver bags."sv,
        "posh salmon bags contain 4 bright purple bags, 5 mirrored green bags, 3 pale gold bags, 5 dull crimson bags."sv,
        "light black bags contain 2 wavy coral bags."sv,
        "striped tan bags contain 3 clear blue bags, 3 mirrored teal bags, 5 striped red bags."sv,
        "posh plum bags contain 3 drab orange bags."sv,
        "striped blue bags contain 4 bright violet bags, 5 dotted gray bags, 3 dotted violet bags, 1 dotted blue bag."sv,
        "shiny white bags contain 4 dotted orange bags, 1 faded silver bag, 1 drab coral bag."sv,
        "plaid maroon bags contain 3 light gold bags."sv,
        "shiny fuchsia bags contain 2 dotted olive bags, 3 vibrant white bags, 3 dark salmon bags, 4 pale white bags."sv,
        "muted bronze bags contain 4 vibrant bronze bags, 2 posh yellow bags, 1 shiny turquoise bag."sv,
        "wavy cyan bags contain 2 striped crimson bags, 4 plaid tan bags."sv,
        "vibrant indigo bags contain 4 pale gold bags, 3 posh gold bags, 1 drab red bag, 4 dull crimson bags."sv,
        "drab tan bags contain 3 dark indigo bags, 3 striped black bags."sv,
        "dull tan bags contain 3 drab blue bags, 3 pale green bags, 3 dotted red bags, 3 striped maroon bags."sv,
        "dark red bags contain 4 bright chartreuse bags."sv,
        "drab beige bags contain 5 bright teal bags, 1 faded cyan bag, 2 muted yellow bags, 1 dim lime bag."sv,
        "dim black bags contain 5 wavy fuchsia bags, 3 muted tomato bags, 4 faded blue bags."sv,
        "pale red bags contain 2 drab gray bags, 5 dull coral bags, 4 striped purple bags."sv,
        "light cyan bags contain 4 mirrored gold bags, 3 vibrant bronze bags."sv,
        "posh orange bags contain 2 dark silver bags, 3 striped chartreuse bags."sv,
        "shiny cyan bags contain 5 dark turquoise bags."sv,
        "vibrant cyan bags contain 2 light turquoise bags, 2 clear cyan bags, 4 dark cyan bags, 4 dotted orange bags."sv,
        "vibrant gray bags contain 5 dark purple bags, 5 dark lime bags."sv,
        "posh green bags contain 4 bright salmon bags, 2 muted tan bags."sv,
        "posh tan bags contain 2 dotted indigo bags, 1 dull purple bag."sv,
        "clear blue bags contain 5 dull purple bags."sv,
        "wavy gray bags contain 4 pale cyan bags, 2 pale tomato bags."sv,
        "posh red bags contain 4 dim green bags, 2 pale teal bags."sv,
        "light tomato bags contain 5 dotted chartreuse bags."sv,
        "faded yellow bags contain 3 plaid orange bags, 4 mirrored maroon bags."sv,
        "dark black bags contain 1 faded gold bag, 3 striped purple bags, 2 dim teal bags."sv,
        "light red bags contain 5 dark magenta bags, 3 striped purple bags."sv,
        "dotted violet bags contain no other bags."sv,
        "faded gold bags contain 1 dotted aqua bag, 2 light turquoise bags, 5 wavy violet bags."sv,
        "dotted beige bags contain 5 vibrant turquoise bags, 5 clear maroon bags, 3 dim tomato bags, 4 pale maroon bags."sv,
        "pale lavender bags contain 5 muted red bags, 3 dark teal bags, 3 faded black bags, 1 dim fuchsia bag."sv,
        "clear tomato bags contain 3 dull white bags, 3 mirrored gold bags, 1 dark black bag."sv,
        "vibrant silver bags contain 4 plaid orange bags, 2 shiny chartreuse bags, 3 dark salmon bags, 4 light silver bags."sv,
        "plaid cyan bags contain 1 dark black bag."sv,
        "drab green bags contain 1 plaid white bag."sv,
        "posh turquoise bags contain 3 posh plum bags, 3 light gold bags, 1 bright crimson bag."sv,
        "pale lime bags contain 3 pale olive bags, 3 vibrant chartreuse bags, 1 dotted tan bag, 5 striped cyan bags."sv,
        "wavy fuchsia bags contain 3 shiny chartreuse bags, 3 vibrant tomato bags, 3 posh salmon bags, 1 light cyan bag."sv,
        "shiny beige bags contain 1 muted orange bag, 3 clear olive bags."sv,
        "posh tomato bags contain 5 muted tomato bags, 5 drab coral bags, 4 pale gold bags."sv,
        "dark fuchsia bags contain 3 wavy blue bags, 5 faded indigo bags."sv,
        "dotted green bags contain 5 dull plum bags, 5 muted lavender bags, 3 faded magenta bags, 4 clear white bags."sv,
        "light salmon bags contain 2 muted purple bags, 5 shiny turquoise bags, 4 muted red bags, 5 posh red bags."sv,
        "plaid purple bags contain 1 muted indigo bag, 4 pale silver bags, 4 dull crimson bags, 1 posh cyan bag."sv,
        "light chartreuse bags contain 2 posh brown bags."sv,
        "dotted black bags contain 3 dull gray bags, 5 muted gray bags, 5 pale maroon bags, 1 vibrant green bag."sv,
        "mirrored teal bags contain 4 light gold bags, 5 striped maroon bags, 2 pale maroon bags."sv,
        "dotted coral bags contain 3 dull teal bags."sv,
        "shiny lime bags contain 3 mirrored gray bags."sv,
        "shiny chartreuse bags contain no other bags."sv,
        "clear red bags contain 4 dim tan bags, 4 dotted brown bags, 2 striped orange bags."sv,
        "clear magenta bags contain 3 pale blue bags, 2 pale crimson bags."sv,
        "faded black bags contain 5 dark turquoise bags."sv,
        "wavy violet bags contain 5 light purple bags."sv,
        "vibrant crimson bags contain 1 shiny gold bag, 1 dotted tomato bag, 1 plaid black bag, 1 drab olive bag."sv,
        "plaid violet bags contain 1 shiny tan bag, 3 muted gray bags, 4 drab chartreuse bags."sv,
        "vibrant lime bags contain 3 dark magenta bags, 2 dotted white bags, 4 muted tan bags."sv,
        "faded violet bags contain 2 drab red bags."sv,
        "plaid black bags contain 2 clear aqua bags, 2 wavy silver bags, 4 dim violet bags, 2 plaid red bags."sv,
        "dull orange bags contain 1 clear tan bag, 1 plaid crimson bag, 1 pale chartreuse bag."sv,
        "vibrant magenta bags contain 4 striped blue bags."sv,
        "plaid fuchsia bags contain 1 vibrant lime bag, 4 faded indigo bags, 2 wavy fuchsia bags, 1 dim purple bag."sv,
        "mirrored olive bags contain 1 dark teal bag, 1 pale brown bag, 1 light violet bag, 1 shiny yellow bag."sv,
        "wavy plum bags contain 5 vibrant cyan bags, 1 pale gold bag, 2 wavy gray bags, 5 pale gray bags."sv,
        "striped magenta bags contain 5 faded silver bags, 1 mirrored teal bag."sv,
        "light indigo bags contain 1 light olive bag."sv,
        "mirrored crimson bags contain 2 vibrant crimson bags."sv,
        "muted crimson bags contain 2 plaid olive bags."sv,
        "muted yellow bags contain 1 muted brown bag, 4 striped lavender bags, 1 bright violet bag."sv,
        "posh lavender bags contain 2 wavy coral bags, 3 light tan bags."sv,
        "striped indigo bags contain 4 dark brown bags."sv,
        "dotted red bags contain 4 pale olive bags, 3 dark teal bags, 1 posh fuchsia bag."sv,
        "plaid indigo bags contain 5 faded gold bags, 4 clear coral bags, 3 dull purple bags, 5 pale brown bags."sv,
        "plaid magenta bags contain 5 faded black bags, 3 drab aqua bags, 5 vibrant green bags."sv,
        "light coral bags contain 1 bright gray bag, 4 wavy orange bags, 2 drab coral bags, 1 dark coral bag."sv,
        "clear brown bags contain 4 plaid aqua bags, 4 plaid coral bags, 5 drab red bags."sv,
        "drab black bags contain 2 dotted white bags, 1 muted purple bag, 3 posh gold bags."sv,
        "dull magenta bags contain 1 dull tomato bag, 4 posh gray bags, 4 wavy white bags, 1 pale cyan bag."sv,
        "muted violet bags contain 3 posh chartreuse bags, 1 dotted magenta bag."sv,
        "vibrant turquoise bags contain 4 plaid brown bags, 5 drab indigo bags, 4 mirrored green bags."sv,
        "striped aqua bags contain 2 posh violet bags, 5 shiny blue bags, 3 pale tomato bags."sv,
        "light teal bags contain 4 faded cyan bags, 2 clear turquoise bags."sv,
        "clear turquoise bags contain 3 shiny aqua bags, 5 posh tomato bags."sv,
        "dark maroon bags contain 2 shiny gold bags, 5 faded green bags."sv,
        "vibrant beige bags contain 5 plaid turquoise bags, 2 shiny gold bags, 2 clear tan bags, 1 wavy black bag."sv,
        "muted chartreuse bags contain 2 muted white bags, 2 striped tan bags, 1 muted brown bag, 5 posh lime bags."sv,
        "pale maroon bags contain 5 pale teal bags, 4 dim violet bags, 5 posh teal bags."sv,
        "vibrant white bags contain 5 light bronze bags, 1 wavy silver bag."sv,
        "plaid olive bags contain 5 mirrored teal bags, 5 faded gray bags, 4 light olive bags."sv,
        "dull silver bags contain 5 clear cyan bags, 1 dim tan bag, 5 dim black bags."sv,
        "bright crimson bags contain 5 dotted indigo bags."sv,
        "muted teal bags contain 3 striped aqua bags, 4 dotted gray bags, 2 bright salmon bags."sv,
        "wavy salmon bags contain 5 posh tomato bags."sv,
        "bright purple bags contain 4 light maroon bags, 2 dotted violet bags."sv,
        "plaid green bags contain 3 faded black bags, 2 plaid red bags, 4 clear turquoise bags."sv,
        "wavy gold bags contain 1 bright white bag."sv,
        "drab violet bags contain 4 vibrant tomato bags."sv,
        "posh maroon bags contain 3 clear tan bags, 3 light gold bags, 1 dim lime bag."sv,
        "muted beige bags contain 4 clear white bags, 5 light maroon bags, 2 clear orange bags."sv,
        "dull turquoise bags contain 4 posh blue bags, 1 mirrored green bag, 5 dotted orange bags, 5 wavy fuchsia bags."sv,
        "shiny red bags contain 4 dark magenta bags."sv,
        "light turquoise bags contain 3 dark cyan bags."sv,
        "posh olive bags contain 3 clear green bags, 5 bright bronze bags, 5 light olive bags."sv,
        "dim chartreuse bags contain 5 vibrant plum bags."sv,
        "dark salmon bags contain 1 dotted orange bag, 3 light brown bags, 3 dotted chartreuse bags."sv,
        "dull teal bags contain 4 wavy gold bags, 5 faded red bags, 4 light turquoise bags."sv,
        "dark green bags contain 3 pale silver bags, 5 clear tan bags."sv,
        "bright cyan bags contain 2 striped maroon bags, 1 clear silver bag, 1 dark maroon bag."sv,
        "wavy crimson bags contain 3 wavy tan bags."sv,
        "mirrored white bags contain 4 mirrored teal bags, 2 muted silver bags."sv,
        "dark magenta bags contain 1 drab blue bag, 4 light white bags, 3 dark black bags."sv,
        "light gold bags contain 4 posh red bags, 1 striped maroon bag, 5 bright purple bags, 4 dotted violet bags."sv,
        "pale tomato bags contain 5 drab coral bags, 3 posh teal bags, 4 dotted blue bags."sv,
        "dull purple bags contain 4 posh gold bags."sv,
        "mirrored gold bags contain 3 mirrored teal bags, 1 striped maroon bag, 2 dotted indigo bags."sv,
        "dotted turquoise bags contain 2 dim violet bags."sv,
        "muted magenta bags contain 1 muted red bag."sv,
        "bright maroon bags contain 3 wavy fuchsia bags, 2 dark magenta bags, 2 dim maroon bags, 1 dotted teal bag."sv,
        "bright aqua bags contain 5 dim green bags, 2 striped tan bags, 1 faded olive bag."sv,
        "striped silver bags contain 5 striped aqua bags, 2 striped purple bags, 3 dim blue bags, 3 faded olive bags."sv,
        "light brown bags contain 4 posh red bags, 3 clear gold bags."sv,
        "dark brown bags contain 4 clear olive bags."sv,
        "dim crimson bags contain 4 dotted teal bags, 3 dark salmon bags."sv,
        "wavy black bags contain 3 drab coral bags, 1 striped purple bag, 2 light brown bags, 4 plaid red bags."sv,
        "striped coral bags contain 2 plaid blue bags, 5 drab tan bags, 5 light violet bags."sv,
        "dull blue bags contain 3 pale gold bags, 1 posh crimson bag."sv,
        "pale blue bags contain 4 dotted blue bags, 3 muted beige bags, 1 faded red bag."sv,
        "mirrored yellow bags contain 4 muted cyan bags, 2 mirrored tan bags."sv,
        "dim maroon bags contain 1 muted aqua bag."sv,
        "drab plum bags contain 2 shiny magenta bags."sv,
        "clear maroon bags contain 2 drab orange bags, 3 shiny red bags, 1 clear brown bag."sv,
        "muted red bags contain 5 pale teal bags, 3 dim fuchsia bags, 1 light maroon bag."sv,
        "dark plum bags contain 5 light salmon bags, 4 dim olive bags."sv,
        "faded indigo bags contain 1 mirrored red bag, 3 faded lime bags."sv,
        "bright coral bags contain 3 posh gold bags, 3 vibrant crimson bags."sv,
        "dark indigo bags contain 5 faded silver bags, 2 dull tomato bags."sv,
        "drab white bags contain 5 light silver bags."sv,
        "vibrant violet bags contain 2 pale gray bags, 4 bright white bags, 3 light aqua bags."sv,
        "mirrored maroon bags contain 1 pale cyan bag, 4 clear bronze bags."sv,
        "wavy chartreuse bags contain 1 bright brown bag, 4 dim lime bags."sv,
        "dull brown bags contain 3 bright olive bags."sv,
        "vibrant yellow bags contain 3 shiny white bags, 2 clear blue bags."sv,
        "posh bronze bags contain 1 light bronze bag."sv,
        "dim aqua bags contain 5 wavy yellow bags, 3 muted purple bags, 3 pale crimson bags."sv,
        "clear gray bags contain 4 faded coral bags, 1 striped violet bag, 5 pale crimson bags, 4 muted lavender bags."sv,
        "muted plum bags contain 4 mirrored cyan bags."sv,
        "dim lime bags contain 2 clear plum bags, 2 dim green bags, 5 posh tan bags."sv,
        "dim red bags contain 2 plaid brown bags."sv,
        "drab bronze bags contain 4 faded plum bags, 4 clear plum bags, 1 posh cyan bag, 1 dark cyan bag."sv,
        "shiny purple bags contain 5 posh beige bags, 4 pale fuchsia bags, 2 wavy brown bags, 2 shiny maroon bags."sv,
        "dull beige bags contain 1 mirrored indigo bag, 2 drab cyan bags, 1 dim fuchsia bag."sv,
        "wavy blue bags contain 4 dotted maroon bags, 3 light maroon bags."sv,
        "faded white bags contain 2 vibrant purple bags, 1 muted purple bag."sv,
        "pale teal bags contain no other bags."sv,
        "bright tan bags contain 3 clear indigo bags, 2 pale orange bags."sv,
        "dull crimson bags contain 3 pale maroon bags, 3 vibrant bronze bags."sv,
        "posh black bags contain 1 muted tomato bag."sv,
        "vibrant maroon bags contain 5 mirrored crimson bags, 4 wavy beige bags."sv,
        "dark lime bags contain 4 dim yellow bags, 1 pale beige bag, 1 vibrant beige bag."sv,
        "bright white bags contain 2 dark turquoise bags."sv,
        "faded plum bags contain 1 vibrant indigo bag, 5 dotted maroon bags, 1 vibrant bronze bag."sv,
        "pale violet bags contain 2 pale lavender bags, 4 light brown bags, 5 vibrant tomato bags."sv,
        "wavy purple bags contain 2 shiny tomato bags, 2 clear maroon bags, 3 posh bronze bags, 4 dull aqua bags."sv,
        "plaid yellow bags contain 4 pale tomato bags, 2 dotted magenta bags, 5 wavy violet bags."sv,
        "bright silver bags contain 5 light gold bags, 2 posh tan bags, 4 faded gray bags."sv,
        "dark orange bags contain 4 dull yellow bags, 5 dull salmon bags."sv,
        "wavy coral bags contain 5 dim lavender bags, 2 mirrored teal bags, 1 shiny chartreuse bag, 2 light gold bags."sv,
        "pale aqua bags contain 1 faded plum bag, 5 vibrant plum bags."sv,
        "dotted brown bags contain 2 light purple bags, 4 dim beige bags, 5 pale white bags."sv,
        "plaid blue bags contain 1 shiny red bag, 5 light silver bags, 5 clear orange bags."sv,
        "dim violet bags contain 3 posh teal bags."sv,
        "dull yellow bags contain 5 muted aqua bags."sv,
        "shiny yellow bags contain 5 muted aqua bags, 2 drab white bags, 5 muted purple bags."sv,
        "dotted maroon bags contain 4 dim green bags, 2 faded silver bags."sv,
        "bright brown bags contain 4 striped bronze bags."sv,
        "posh crimson bags contain 2 posh red bags, 1 dotted indigo bag, 4 muted red bags."sv,
        "dim orange bags contain 2 light tan bags, 4 dotted salmon bags."sv,
        "mirrored beige bags contain 4 dim bronze bags, 5 vibrant salmon bags, 4 dim maroon bags."sv,
        "shiny olive bags contain 5 dotted orange bags."sv,
        "wavy tan bags contain 1 wavy brown bag, 1 faded silver bag."sv,
        "mirrored magenta bags contain 5 drab teal bags, 3 striped bronze bags, 3 striped magenta bags, 5 dark tan bags."sv,
        "muted brown bags contain 1 light indigo bag, 4 dotted blue bags."sv,
        "vibrant aqua bags contain 1 shiny red bag, 5 wavy gold bags."sv,
        "dark violet bags contain 2 dim orange bags, 5 dark purple bags, 2 pale yellow bags."sv,
        "plaid teal bags contain 3 vibrant bronze bags."sv,
        "shiny gold bags contain 5 drab red bags, 2 mirrored green bags, 2 muted tomato bags, 1 striped magenta bag."sv,
        "wavy bronze bags contain 2 vibrant green bags, 2 plaid orange bags, 2 vibrant orange bags."sv,
        "dark tomato bags contain 4 posh indigo bags."sv,
        "drab red bags contain no other bags."sv,
        "clear silver bags contain 1 plaid olive bag."sv,
        "striped cyan bags contain 3 wavy silver bags, 2 faded indigo bags."sv,
        "dark purple bags contain 1 wavy violet bag, 5 clear olive bags, 3 drab indigo bags, 5 striped purple bags."sv,
        "dotted plum bags contain 4 vibrant purple bags, 3 muted lavender bags, 1 wavy coral bag."sv,
        "posh yellow bags contain 5 light salmon bags, 2 light bronze bags."sv,
        "dim tomato bags contain 3 pale white bags."sv,
        "drab lime bags contain 3 drab chartreuse bags, 4 clear silver bags, 4 drab aqua bags."sv,
        "plaid coral bags contain 2 bright olive bags."sv,
        "mirrored salmon bags contain 3 plaid green bags."sv,
        "faded chartreuse bags contain 2 light cyan bags, 5 pale tomato bags."sv,
        "pale crimson bags contain 5 bright white bags, 3 shiny turquoise bags."sv,
        "pale brown bags contain 4 bright silver bags."sv,
        "shiny bronze bags contain 5 dull chartreuse bags, 4 dotted gray bags, 3 shiny blue bags, 1 dull blue bag."sv,
        "faded red bags contain 2 muted gray bags."sv,
        "dark lavender bags contain 5 dim coral bags, 4 muted gray bags, 1 shiny yellow bag."sv,
        "faded purple bags contain 2 dotted white bags."sv,
        "mirrored silver bags contain 3 pale maroon bags, 2 pale cyan bags, 4 dark chartreuse bags, 3 bright plum bags."sv,
        "dull violet bags contain 1 dim coral bag, 3 wavy lavender bags."sv,
        "faded beige bags contain 4 plaid bronze bags, 1 light salmon bag, 2 light brown bags."sv,
        "vibrant orange bags contain 1 faded cyan bag, 2 vibrant olive bags, 2 bright plum bags."sv,
        "vibrant purple bags contain 5 dotted orange bags, 1 striped aqua bag, 4 clear white bags, 3 dim olive bags."sv,
        "faded crimson bags contain 1 clear lavender bag, 3 dim lavender bags, 3 dim cyan bags, 2 wavy tan bags."sv,
        "dark yellow bags contain 1 plaid silver bag, 3 wavy maroon bags."sv,
        "vibrant brown bags contain 5 dotted chartreuse bags, 4 clear silver bags, 4 dull lavender bags."sv,
        "wavy lavender bags contain 4 dull gray bags."sv,
        "bright green bags contain 5 striped gold bags."sv,
        "faded magenta bags contain 5 dull beige bags."sv,
        "posh white bags contain 2 dark coral bags."sv,
        "muted green bags contain 1 wavy lavender bag, 1 striped aqua bag."sv,
        "plaid turquoise bags contain 1 striped brown bag, 4 mirrored maroon bags."sv,
        "plaid lavender bags contain 4 striped tan bags, 2 posh brown bags, 5 shiny brown bags."sv,
        "pale fuchsia bags contain 5 light brown bags, 3 vibrant lime bags."sv,
        "light gray bags contain 3 drab violet bags."sv,
        "dim green bags contain no other bags."sv,
        "light olive bags contain 4 vibrant bronze bags."sv,
        "dotted aqua bags contain 5 muted red bags."sv,
        "vibrant fuchsia bags contain 5 dull crimson bags, 5 dotted violet bags."sv,
        "clear crimson bags contain 5 dotted tomato bags, 3 posh crimson bags, 5 vibrant magenta bags."sv,
        "pale orange bags contain 5 mirrored indigo bags, 5 muted purple bags, 4 plaid orange bags."sv,
        "mirrored lavender bags contain 4 dotted orange bags, 3 posh violet bags."sv,
        "dotted tan bags contain 5 mirrored gray bags."sv,
        "dim bronze bags contain 3 mirrored olive bags, 3 plaid magenta bags, 5 dim black bags, 2 drab blue bags."sv,
        "clear olive bags contain 3 bright purple bags, 4 dim lime bags, 5 dim fuchsia bags."sv,
        "dotted blue bags contain 1 dim green bag, 3 drab red bags, 2 posh gold bags."sv,
        "shiny gray bags contain 3 pale lavender bags, 1 clear gold bag, 2 drab violet bags, 2 clear bronze bags."sv,
        "bright plum bags contain 3 muted yellow bags, 4 posh chartreuse bags, 3 posh brown bags, 3 dim orange bags."sv,
        "shiny violet bags contain 5 dim coral bags."sv,
        "posh lime bags contain 3 plaid silver bags."sv,
        "light beige bags contain 5 pale yellow bags, 3 light bronze bags, 5 pale turquoise bags."sv,
        "drab gray bags contain 4 bright purple bags, 5 faded gold bags, 2 dim green bags."sv,
        "muted aqua bags contain 4 clear white bags."sv,
        "mirrored blue bags contain 2 vibrant green bags, 2 drab gray bags."sv,
        "posh magenta bags contain 2 striped magenta bags, 5 dim cyan bags, 5 plaid orange bags, 1 wavy black bag."sv,
        "dim yellow bags contain 2 muted purple bags, 1 striped black bag, 3 wavy coral bags."sv,
        "dull indigo bags contain 3 posh fuchsia bags, 1 dotted beige bag."sv,
        "posh gray bags contain 5 drab black bags."sv,
        "dark blue bags contain 4 dim gold bags, 3 drab olive bags, 1 light cyan bag, 2 light tomato bags."sv,
        "mirrored red bags contain 5 shiny white bags, 1 mirrored green bag, 4 wavy black bags, 1 dark brown bag."sv,
        "mirrored violet bags contain 3 dim tan bags, 4 dark fuchsia bags, 4 pale turquoise bags."sv,
        "shiny black bags contain 5 clear orange bags, 2 vibrant silver bags, 2 plaid maroon bags, 3 light olive bags."sv,
        "vibrant chartreuse bags contain 4 dull salmon bags, 3 bright beige bags, 1 faded blue bag, 2 plaid brown bags."sv,
        "dull cyan bags contain 3 faded green bags."sv,
        "bright gold bags contain 3 posh plum bags."sv,
        "vibrant olive bags contain 5 mirrored coral bags, 3 dotted lime bags, 5 drab blue bags, 2 dotted green bags."sv,
        "faded maroon bags contain 4 mirrored green bags, 2 light lime bags, 3 light bronze bags."sv,
        "vibrant red bags contain 2 posh lime bags, 1 dull maroon bag."sv,
        "dull bronze bags contain 5 vibrant chartreuse bags."sv,
        "vibrant bronze bags contain 2 vibrant tomato bags, 3 mirrored teal bags."sv,
        "pale black bags contain 1 muted silver bag, 5 mirrored teal bags, 2 shiny blue bags."sv,
        "dull maroon bags contain 1 clear cyan bag."sv,
        "dotted crimson bags contain 5 posh black bags, 1 dotted teal bag, 4 vibrant salmon bags, 4 shiny silver bags."sv,
        "striped tomato bags contain 5 drab tomato bags, 2 faded coral bags, 2 dim salmon bags."sv,
        "bright bronze bags contain 5 plaid red bags, 4 striped yellow bags."sv,
        "dark aqua bags contain 4 bright purple bags, 1 striped gold bag."sv,
        "striped teal bags contain 4 striped black bags, 3 clear indigo bags."sv,
        "dark olive bags contain 2 pale cyan bags, 5 mirrored tan bags."sv,
        "dark teal bags contain 1 posh gold bag, 1 plaid orange bag, 1 vibrant bronze bag, 1 mirrored teal bag."sv,
        "faded green bags contain 5 vibrant fuchsia bags, 3 dim olive bags."sv,
        "posh brown bags contain 4 drab lime bags, 2 mirrored fuchsia bags, 3 shiny lime bags, 2 dim violet bags."sv,
        "striped lavender bags contain 2 plaid red bags, 5 dark brown bags, 3 clear turquoise bags."sv,
        "shiny indigo bags contain 2 striped lavender bags, 1 light gray bag."sv,
        "plaid orange bags contain 1 pale teal bag, 5 dim violet bags, 5 vibrant bronze bags, 3 light maroon bags."sv,
        "dull salmon bags contain 1 striped bronze bag, 4 shiny aqua bags, 4 dark brown bags."sv,
        "plaid white bags contain 1 dim green bag."sv,
        "drab lavender bags contain 2 dotted maroon bags, 3 pale aqua bags, 1 light olive bag."sv,
        "striped olive bags contain 5 striped magenta bags."sv,
        "mirrored gray bags contain 2 dim lavender bags, 2 shiny chartreuse bags."sv,
        "dull coral bags contain 1 mirrored gold bag, 5 clear gold bags, 5 clear olive bags, 2 posh tomato bags."sv,
        "pale beige bags contain 2 dark indigo bags, 4 dim beige bags."sv,
        "posh teal bags contain 1 dim green bag, 3 dim fuchsia bags, 1 pale teal bag, 2 dotted indigo bags."sv,
        "mirrored turquoise bags contain 4 dim olive bags, 2 plaid tomato bags."sv,
        "dim turquoise bags contain 2 bright yellow bags, 1 striped lavender bag."sv,
        "light violet bags contain 4 faded gold bags, 3 clear plum bags, 1 dark teal bag."sv,
        "dark cyan bags contain 3 drab red bags, 4 pale maroon bags."sv,
        "shiny crimson bags contain 5 dotted turquoise bags, 1 vibrant fuchsia bag, 5 dotted lime bags, 2 wavy green bags."sv,
        "muted lime bags contain 2 light brown bags, 5 plaid tomato bags, 4 plaid aqua bags."sv,
        "vibrant tan bags contain 4 wavy fuchsia bags."sv,
        "wavy maroon bags contain 4 dull white bags, 5 dark crimson bags, 5 mirrored salmon bags, 4 vibrant purple bags."sv,
        "muted indigo bags contain 5 shiny red bags."sv,
        "clear violet bags contain 2 plaid green bags."sv,
        "drab teal bags contain 2 pale cyan bags, 1 shiny turquoise bag."sv,
        "wavy green bags contain 5 plaid indigo bags, 3 muted silver bags, 5 light brown bags."sv,
        "striped crimson bags contain 3 shiny aqua bags."sv,
        "drab purple bags contain 3 drab orange bags, 3 dark aqua bags, 1 bright lavender bag."sv,
        "plaid aqua bags contain 1 plaid tomato bag."sv,
        "striped green bags contain 2 vibrant tomato bags, 2 faded plum bags."sv,
        "drab tomato bags contain 4 posh black bags, 3 dull brown bags, 1 drab cyan bag."sv,
        "dotted bronze bags contain 1 clear indigo bag."sv,
        "pale white bags contain 5 mirrored green bags, 2 dark turquoise bags, 3 dull olive bags, 4 drab indigo bags."sv,
        "drab yellow bags contain 2 dotted orange bags, 4 light turquoise bags, 4 light salmon bags, 2 dotted tomato bags."sv,
        "pale green bags contain 3 muted gold bags, 3 shiny turquoise bags."sv,
        "dark tan bags contain 4 muted cyan bags, 5 dotted tomato bags, 2 dark indigo bags."sv,
        "plaid tan bags contain 4 vibrant olive bags, 1 plaid aqua bag, 3 dotted coral bags, 4 bright violet bags."sv,
        "shiny aqua bags contain 2 dull brown bags, 1 vibrant cyan bag, 2 dim lime bags, 5 light bronze bags."sv,
        "bright turquoise bags contain 2 plaid yellow bags, 3 posh lavender bags, 1 pale yellow bag."sv,
        "vibrant gold bags contain 1 clear tomato bag, 4 clear turquoise bags, 4 dark bronze bags."sv,
        "posh cyan bags contain 3 dotted green bags, 5 plaid tomato bags, 3 wavy crimson bags, 2 striped olive bags."sv,
        "clear salmon bags contain 3 plaid fuchsia bags, 5 muted bronze bags, 5 dull green bags, 2 pale brown bags."sv,
        "drab maroon bags contain 5 dull crimson bags, 2 shiny white bags, 5 light purple bags."sv,
        "clear tan bags contain 5 dull lime bags, 5 muted red bags, 2 clear cyan bags."sv,
        "pale gray bags contain 3 shiny white bags."sv,
        "vibrant teal bags contain 1 clear green bag, 1 dull beige bag."sv,
        "vibrant plum bags contain 4 muted red bags, 2 faded blue bags, 5 vibrant tomato bags."sv,
        "dark coral bags contain 2 plaid tomato bags, 1 bright yellow bag, 2 mirrored gray bags."sv,
        "wavy indigo bags contain 1 mirrored tan bag, 1 wavy lavender bag."sv,
        "dotted fuchsia bags contain 2 vibrant silver bags, 3 mirrored tan bags."sv,
        "muted gold bags contain 3 muted red bags, 1 clear olive bag."sv,
        "striped fuchsia bags contain 2 clear aqua bags, 4 mirrored coral bags, 3 muted gray bags, 2 dark beige bags."sv,
        "striped maroon bags contain no other bags."sv,
        "bright lavender bags contain 2 faded indigo bags, 1 dotted violet bag, 5 posh tomato bags, 3 clear indigo bags."sv,
        "posh gold bags contain 1 dim violet bag, 2 shiny chartreuse bags."sv,
        "drab olive bags contain 4 faded silver bags."sv,
        "pale chartreuse bags contain 4 striped teal bags."sv,
        "mirrored lime bags contain 5 dotted plum bags, 1 light yellow bag, 3 pale fuchsia bags."sv,
        "clear bronze bags contain 4 plaid brown bags."sv,
        "wavy tomato bags contain 4 faded lavender bags, 3 dull aqua bags, 1 drab green bag, 3 vibrant gray bags."sv,
        "dim brown bags contain 4 dull teal bags, 2 vibrant black bags, 1 mirrored gold bag."sv,
        "bright fuchsia bags contain 4 faded lavender bags, 1 dull crimson bag, 1 mirrored brown bag, 5 dark indigo bags."sv,
        "muted gray bags contain 1 dull olive bag."sv,
        "dull white bags contain 1 light maroon bag, 4 dark lavender bags, 2 posh red bags."sv,
        "dull black bags contain 5 dark green bags, 4 bright lime bags, 4 mirrored gray bags."sv,
        "dull tomato bags contain 4 dotted tomato bags."sv,
        "pale coral bags contain 1 mirrored white bag, 5 clear aqua bags, 4 dim blue bags."sv,
        "posh indigo bags contain 2 bright bronze bags."sv,
        "plaid gold bags contain 4 dark maroon bags, 4 shiny lavender bags, 1 plaid tomato bag, 3 bright yellow bags."sv,
        "plaid gray bags contain 4 muted bronze bags, 2 posh chartreuse bags, 5 pale tomato bags, 3 drab coral bags."sv,
        "dim beige bags contain 4 dim blue bags, 4 dark lavender bags."sv,
        "bright olive bags contain no other bags."sv,
        "clear aqua bags contain 4 wavy fuchsia bags, 5 dim green bags."sv,
        "posh violet bags contain 2 vibrant indigo bags, 3 posh tomato bags, 4 clear gold bags, 5 dim green bags."sv,
        "faded coral bags contain 4 light purple bags, 4 mirrored salmon bags, 5 pale maroon bags."sv,
        "dotted chartreuse bags contain 2 clear aqua bags, 4 plaid coral bags."sv,
        "striped orange bags contain 5 bright tan bags, 5 pale white bags, 5 mirrored lavender bags."sv,
        "bright tomato bags contain 5 muted white bags."sv,
        "shiny silver bags contain 1 dotted orange bag, 2 light olive bags, 1 striped gold bag."sv,
        "striped yellow bags contain 1 shiny turquoise bag."sv,
        "faded aqua bags contain 5 shiny cyan bags, 3 dotted indigo bags, 4 faded fuchsia bags."sv,
        "striped beige bags contain 1 bright white bag, 5 dim lavender bags, 5 striped black bags, 1 wavy black bag."sv,
        "shiny orange bags contain 4 dark aqua bags."sv,
        "striped white bags contain 3 vibrant fuchsia bags, 1 dotted teal bag, 5 dotted green bags, 2 shiny white bags."sv,
        "bright black bags contain 5 pale blue bags, 2 drab teal bags, 1 dull gray bag."sv,
        "shiny lavender bags contain 1 pale gold bag, 2 bright crimson bags, 2 pale maroon bags."sv,
        "shiny maroon bags contain 2 wavy white bags, 2 muted aqua bags, 3 plaid gold bags."sv,
        "drab cyan bags contain 4 posh crimson bags, 5 drab red bags, 5 bright purple bags."sv,
        "dark bronze bags contain 5 posh teal bags."sv,
        "shiny turquoise bags contain 2 shiny gold bags, 5 mirrored teal bags, 5 mirrored gray bags, 1 drab cyan bag."sv,
        "dark turquoise bags contain 1 dim violet bag, 5 mirrored teal bags."sv,
        "light lime bags contain 4 drab chartreuse bags."sv,
        "light yellow bags contain 5 wavy olive bags, 2 wavy gray bags, 4 bright red bags, 5 shiny violet bags."sv,
        "posh aqua bags contain 3 vibrant salmon bags."sv,
        "drab silver bags contain 3 pale tan bags."sv,
        "pale tan bags contain 3 wavy white bags."sv,
        "light white bags contain 4 wavy black bags, 2 dark teal bags, 2 faded blue bags."sv,
        "shiny teal bags contain 5 wavy gold bags."sv,
        "shiny tomato bags contain 3 faded violet bags."sv,
        "wavy brown bags contain 1 dim black bag, 1 bright yellow bag."sv,
        "dim tan bags contain 2 clear teal bags, 5 drab teal bags, 4 posh lime bags."sv,
        "faded cyan bags contain 1 pale plum bag, 4 posh gold bags, 4 posh yellow bags."sv,
        "dotted magenta bags contain 4 drab tomato bags, 5 drab yellow bags, 2 clear maroon bags."sv,
        "clear green bags contain 5 striped maroon bags, 4 shiny aqua bags."sv,
        "clear fuchsia bags contain 5 dotted chartreuse bags, 5 pale plum bags, 2 muted red bags."sv,
        "bright lime bags contain 3 dark salmon bags, 3 bright cyan bags, 4 striped black bags, 4 posh violet bags."sv,
        "bright violet bags contain 1 light olive bag, 2 dark coral bags, 1 dull beige bag, 5 plaid maroon bags."sv,
        "vibrant lavender bags contain 5 dim green bags, 1 plaid violet bag, 4 dotted coral bags."sv,
        "wavy silver bags contain 2 mirrored green bags, 4 clear olive bags, 5 dark beige bags, 5 plaid orange bags."sv,
        "clear orange bags contain 4 dotted orange bags, 3 bright silver bags, 5 dotted tomato bags, 4 striped purple bags."sv,
        "light crimson bags contain 5 striped teal bags, 1 striped coral bag, 1 pale tomato bag, 2 dark crimson bags."sv,
        "bright gray bags contain 3 posh tan bags."sv,
        "mirrored indigo bags contain 1 mirrored green bag."sv,
        "dull chartreuse bags contain 4 pale gold bags, 2 drab lavender bags, 3 shiny cyan bags."sv,
        "pale salmon bags contain 5 drab purple bags, 2 dark olive bags, 4 mirrored silver bags."sv,
        "bright indigo bags contain 5 striped beige bags, 5 shiny lime bags."sv,
        "dim lavender bags contain 5 striped maroon bags."sv,
        "bright magenta bags contain 2 plaid coral bags, 5 shiny aqua bags, 1 light purple bag."sv,
        "muted purple bags contain 4 shiny turquoise bags, 1 shiny chartreuse bag, 3 muted tomato bags, 1 dotted aqua bag."sv,
        "muted cyan bags contain 4 wavy black bags, 2 faded plum bags, 1 dull coral bag, 3 light tomato bags."sv,
        "shiny plum bags contain 5 pale gray bags, 3 vibrant aqua bags."sv,
        "dull lime bags contain 4 drab cyan bags, 1 posh gold bag, 4 bright purple bags, 3 posh tan bags."sv,
        "faded teal bags contain 3 bright purple bags, 4 dotted magenta bags, 4 plaid olive bags."sv,
        "clear chartreuse bags contain 2 dark brown bags, 1 pale lavender bag, 2 dark coral bags."sv,
        "dotted tomato bags contain 1 dim green bag, 2 posh tomato bags."sv,
        "pale silver bags contain 2 pale teal bags, 4 light purple bags, 4 bright yellow bags, 4 clear plum bags."sv,
        "posh purple bags contain 2 faded tan bags, 3 clear aqua bags, 4 striped lavender bags, 3 dark teal bags."sv,
        "striped bronze bags contain 4 drab red bags, 5 mirrored gray bags."sv,
        "striped black bags contain 3 wavy coral bags, 3 faded blue bags, 5 bright olive bags, 2 dark bronze bags."sv,
        "dark chartreuse bags contain 5 posh tomato bags."sv,
        "muted white bags contain 2 mirrored gray bags, 5 dark cyan bags, 3 dotted indigo bags."sv,
        "clear indigo bags contain 3 dark coral bags, 1 pale green bag, 2 plaid orange bags, 4 dim lime bags."sv,
        "faded tan bags contain 3 dull purple bags, 2 dim orange bags."sv,
        "clear yellow bags contain 1 vibrant fuchsia bag, 5 faded silver bags, 5 faded black bags."sv,
        "dark gray bags contain 5 striped cyan bags."sv,
        "clear plum bags contain 2 drab indigo bags, 5 pale maroon bags."sv,
        "posh fuchsia bags contain 2 muted lavender bags, 5 posh red bags."sv,
        "vibrant black bags contain 1 posh gold bag, 1 shiny white bag."sv,
        "dim salmon bags contain 5 muted tan bags, 2 muted green bags, 2 pale bronze bags."sv,
        "faded brown bags contain 3 dim tan bags."sv,
        "mirrored brown bags contain 1 drab bronze bag, 3 wavy coral bags, 4 posh fuchsia bags."sv,
        "dim gold bags contain 2 mirrored lavender bags, 5 pale gray bags."sv,
        "faded fuchsia bags contain 3 wavy lavender bags, 5 shiny blue bags, 4 muted tomato bags."sv,
        "mirrored chartreuse bags contain 2 faded aqua bags, 4 dark coral bags, 4 wavy beige bags, 5 dark orange bags."sv,
        "muted fuchsia bags contain 3 light olive bags."sv,
        "dotted silver bags contain 5 dotted turquoise bags, 3 dark cyan bags, 2 plaid red bags."sv,
        "plaid lime bags contain 5 dull blue bags."sv,
        "dim gray bags contain 4 striped magenta bags, 3 dotted indigo bags, 2 dim violet bags, 3 light olive bags."sv,
        "wavy lime bags contain 2 bright salmon bags, 3 shiny cyan bags, 4 light gray bags, 4 shiny plum bags."sv,
        "striped lime bags contain 5 posh teal bags."sv,
        "dull red bags contain 3 mirrored tan bags, 3 dim tomato bags, 5 striped crimson bags."sv,
        "faded lavender bags contain 1 bright indigo bag, 1 dim purple bag, 5 mirrored gray bags, 4 clear cyan bags."sv,
        "wavy aqua bags contain 1 wavy gray bag, 3 dark crimson bags."sv,
        "faded turquoise bags contain 1 drab plum bag, 5 dull gray bags, 4 plaid black bags, 1 wavy crimson bag."sv,
        "dotted salmon bags contain 4 posh teal bags."sv,
        "clear coral bags contain 5 drab tomato bags."sv,
        "vibrant blue bags contain 4 dim lavender bags, 4 dark cyan bags."sv,
        "muted coral bags contain 5 vibrant olive bags, 1 clear plum bag, 1 clear blue bag."sv,
        "vibrant coral bags contain 5 vibrant silver bags, 2 plaid brown bags, 4 wavy brown bags."sv,
        "mirrored aqua bags contain 4 bright lavender bags, 4 striped lavender bags, 1 posh fuchsia bag."sv,
        "clear gold bags contain 1 posh tan bag, 1 dark beige bag, 5 striped gold bags."sv,
        "dull aqua bags contain 4 dull plum bags, 2 light indigo bags."sv,
        "clear cyan bags contain 5 light maroon bags, 5 posh tan bags, 3 dim lavender bags."sv,
        "dotted olive bags contain 1 mirrored maroon bag, 2 dotted red bags, 4 drab lime bags."sv,
        "wavy yellow bags contain 4 light silver bags, 4 dotted orange bags."sv,
        "faded salmon bags contain 1 shiny lavender bag, 4 muted tomato bags, 3 plaid coral bags, 3 pale green bags."sv,
        "dim blue bags contain 2 dim black bags."sv,
        "faded tomato bags contain 3 shiny magenta bags."sv,
        "light magenta bags contain 5 dim olive bags, 3 muted lavender bags."sv,
        "muted turquoise bags contain 4 posh gold bags, 2 wavy beige bags, 3 posh magenta bags."sv,
        "light purple bags contain 3 light maroon bags."sv,
        "pale indigo bags contain 2 light green bags, 5 plaid bronze bags."sv,
        "dim fuchsia bags contain no other bags."sv,
        "plaid chartreuse bags contain 3 shiny silver bags, 1 posh teal bag."sv,
        "plaid salmon bags contain 5 drab lime bags, 4 light aqua bags, 2 striped tan bags."sv,
        "drab coral bags contain no other bags."sv,
        "dotted gold bags contain 2 clear teal bags, 2 posh salmon bags, 1 plaid green bag, 5 muted tomato bags."sv,
        "dull olive bags contain 2 dim lavender bags."sv,
        "dotted purple bags contain 5 vibrant white bags, 5 wavy black bags."sv,
        "dark crimson bags contain 4 posh chartreuse bags, 3 muted green bags, 3 dull plum bags, 5 muted beige bags."sv,
        "mirrored tomato bags contain 2 clear crimson bags, 4 mirrored indigo bags, 2 muted black bags, 2 dark gray bags."sv,
        "muted blue bags contain 5 pale brown bags."sv,
        "wavy beige bags contain 5 plaid red bags."sv,
        "muted black bags contain 3 muted magenta bags, 2 clear tomato bags, 1 pale red bag."sv,
        "mirrored bronze bags contain 5 bright olive bags, 5 vibrant cyan bags, 2 drab cyan bags."sv,
        "vibrant green bags contain 2 dull brown bags, 4 wavy white bags, 3 pale teal bags, 4 dark bronze bags."sv,
        "dotted orange bags contain 5 light gold bags, 5 vibrant tomato bags, 3 light silver bags, 4 drab cyan bags."sv,
        "clear purple bags contain 4 dull fuchsia bags."sv,
        "mirrored green bags contain 2 muted red bags, 2 dim lavender bags."sv,
        "wavy red bags contain 1 posh yellow bag, 2 shiny coral bags."sv,
        "drab chartreuse bags contain 5 dull purple bags, 2 bright purple bags, 3 faded silver bags, 4 muted lavender bags."sv,
        "dim indigo bags contain 1 light red bag, 4 wavy olive bags."sv,
        "drab crimson bags contain 5 muted indigo bags, 5 vibrant crimson bags."sv,
        "wavy olive bags contain 3 light black bags, 2 wavy plum bags."sv,
        "dark silver bags contain 4 dull fuchsia bags, 3 dotted chartreuse bags."sv,
        "pale olive bags contain 1 dark purple bag, 1 drab yellow bag, 1 vibrant coral bag."sv,
        "posh silver bags contain 4 faded magenta bags, 5 muted coral bags, 4 posh cyan bags, 2 faded gray bags."sv,
        "clear white bags contain 4 shiny blue bags."sv,
        "light silver bags contain 3 mirrored green bags, 2 muted red bags, 1 muted tomato bag, 3 clear olive bags."sv,
        "faded gray bags contain 5 dim green bags, 5 pale teal bags, 4 posh crimson bags, 3 dotted indigo bags."sv,
        "clear teal bags contain 2 posh chartreuse bags, 2 posh blue bags."sv,
        "dull green bags contain 5 muted tan bags, 3 faded gray bags, 2 dark tan bags."sv,
        "dotted yellow bags contain 1 dim aqua bag, 5 dotted blue bags, 1 plaid teal bag, 2 dim salmon bags."sv,
        "dotted indigo bags contain 1 muted red bag."sv,
        "pale gold bags contain 1 mirrored green bag, 2 faded gray bags, 4 drab olive bags."sv,
        "pale magenta bags contain 1 pale gray bag."sv,
        "drab orange bags contain 4 dull beige bags, 1 dim gray bag."sv,
        "light maroon bags contain no other bags."sv,
        "dim silver bags contain 2 dull olive bags, 2 muted lavender bags, 5 dark fuchsia bags, 5 dotted tan bags."sv,
        "shiny magenta bags contain 5 light purple bags."sv,
        "shiny green bags contain 2 dim green bags, 1 pale plum bag, 2 striped teal bags."sv,
        "drab magenta bags contain 1 plaid yellow bag, 3 bright crimson bags, 4 shiny salmon bags."sv,
        "shiny salmon bags contain 4 dark bronze bags, 1 pale aqua bag, 5 posh red bags, 2 light gold bags."sv,
        "mirrored cyan bags contain 2 bright olive bags, 2 bright aqua bags, 4 shiny turquoise bags."sv,
        "drab aqua bags contain 1 drab olive bag, 5 shiny white bags, 2 dim gray bags."sv,
        "wavy white bags contain 1 plaid red bag."sv,
        "clear black bags contain 1 dim fuchsia bag, 5 pale white bags, 3 drab fuchsia bags."sv,
        "dotted cyan bags contain 3 wavy aqua bags, 4 shiny brown bags, 4 faded tan bags."sv,
        "dim magenta bags contain 4 striped orange bags, 2 mirrored turquoise bags, 3 vibrant turquoise bags, 3 pale chartreuse bags."sv,
        "faded silver bags contain 5 dim fuchsia bags, 2 bright purple bags."sv,
        "faded olive bags contain 3 dull lavender bags, 2 striped salmon bags, 1 bright yellow bag."sv,
        "faded lime bags contain 4 posh tan bags, 4 dotted lavender bags, 3 striped magenta bags."sv,
        "dark white bags contain 2 bright beige bags, 3 shiny chartreuse bags."sv,
        "striped brown bags contain 5 muted lavender bags."sv,
        "dotted lime bags contain 1 mirrored green bag, 4 dotted chartreuse bags, 2 shiny cyan bags, 1 bright purple bag."sv,
        "bright beige bags contain 4 dull gray bags, 3 wavy violet bags, 5 light silver bags, 5 drab white bags."sv,
        "dark beige bags contain 3 light gold bags, 1 muted tomato bag, 4 pale teal bags, 4 posh crimson bags."sv,
        "dim olive bags contain 4 dark cyan bags."sv,
        "plaid plum bags contain 1 clear tan bag, 4 posh brown bags."sv,
        "wavy magenta bags contain 4 dotted plum bags, 2 dull tan bags."sv,
        "drab gold bags contain 4 dark cyan bags, 2 clear yellow bags."sv,
        "muted orange bags contain 2 faded tan bags, 5 vibrant salmon bags."sv,
        "pale yellow bags contain 3 light turquoise bags, 3 plaid maroon bags, 2 dull salmon bags."sv,
        "plaid tomato bags contain 2 dark beige bags."sv,
        "dim purple bags contain 5 posh salmon bags, 2 dim lime bags, 2 dotted white bags."sv,
        "bright red bags contain 4 dark teal bags, 3 shiny cyan bags."sv,
        "bright salmon bags contain 4 pale aqua bags, 3 clear orange bags, 3 plaid black bags, 5 faded aqua bags."sv,
        "plaid crimson bags contain 4 plaid tan bags, 4 dim aqua bags."sv,
        "striped violet bags contain 2 dotted olive bags, 2 dotted red bags, 4 shiny gold bags."sv,
        "vibrant tomato bags contain 3 dim lime bags."sv,
        "drab turquoise bags contain 5 shiny purple bags, 1 light green bag, 1 pale chartreuse bag."sv,
        "wavy turquoise bags contain 1 dark teal bag, 5 shiny fuchsia bags, 4 muted brown bags, 4 bright green bags."sv,
        "striped plum bags contain 3 bright chartreuse bags, 1 dotted violet bag, 1 posh maroon bag."sv,
        "mirrored plum bags contain 4 plaid indigo bags, 5 dotted white bags."sv,
        "muted salmon bags contain 5 faded magenta bags, 3 plaid blue bags."sv,
        "shiny brown bags contain 3 drab salmon bags."sv,
        "drab blue bags contain 3 drab olive bags, 5 muted red bags, 2 bright purple bags."sv,
        "striped gray bags contain 3 clear olive bags, 2 muted coral bags."sv,
        "bright yellow bags contain 2 dull olive bags, 5 dark turquoise bags, 5 posh teal bags."sv,
        "dim plum bags contain 2 dim cyan bags, 5 vibrant crimson bags."sv,
        "muted lavender bags contain 2 clear bronze bags."sv,
        "muted silver bags contain 3 vibrant salmon bags, 5 muted cyan bags, 1 dotted black bag."sv,
        "mirrored orange bags contain 2 dull olive bags, 4 striped beige bags, 3 shiny aqua bags, 2 striped salmon bags."sv,
        "dim teal bags contain 2 drab blue bags."sv,
        "plaid brown bags contain 1 pale maroon bag, 4 light salmon bags, 1 vibrant indigo bag, 5 clear cyan bags."sv,
        "bright chartreuse bags contain 4 plaid coral bags, 2 dull crimson bags, 3 plaid aqua bags, 2 faded blue bags."sv,
        "dotted gray bags contain 1 dotted indigo bag, 2 posh crimson bags."sv,
        "drab indigo bags contain 1 dotted violet bag, 1 dim fuchsia bag, 4 muted red bags, 4 striped maroon bags."sv,
        "plaid bronze bags contain 3 drab plum bags, 1 posh violet bag, 2 dark tan bags, 3 plaid white bags."sv,
        "striped salmon bags contain 3 clear brown bags."sv,
        "dull lavender bags contain 4 pale green bags."sv,
        "dull gray bags contain 4 drab indigo bags, 4 light salmon bags, 2 plaid coral bags, 3 striped magenta bags."sv,
        "mirrored purple bags contain 2 vibrant brown bags, 1 plaid teal bag, 4 drab red bags, 4 plaid turquoise bags."sv,
        "dull gold bags contain 3 drab teal bags."sv,
        "light fuchsia bags contain 2 clear tan bags, 1 posh tan bag."sv,
        "dim white bags contain 1 bright beige bag."sv,
        "light green bags contain 1 dotted red bag, 4 muted gray bags, 5 dotted orange bags, 3 dim chartreuse bags."sv,
        "bright teal bags contain 5 bright bronze bags, 2 pale green bags."sv,
        "striped purple bags contain 1 dark beige bag."sv,
        "muted tan bags contain 4 pale silver bags, 2 bright lavender bags, 4 drab cyan bags."sv,
        "light blue bags contain 5 drab white bags, 1 pale olive bag."sv,
        "dim cyan bags contain 1 wavy fuchsia bag, 5 posh teal bags."sv,
        "striped chartreuse bags contain 4 bright beige bags, 1 muted lavender bag."sv,
        "light lavender bags contain 2 posh lavender bags, 1 dim lavender bag."sv,
        "striped gold bags contain 1 posh salmon bag, 3 mirrored gray bags, 1 faded silver bag."sv,
        "light orange bags contain 4 dark black bags."sv,
        "plaid silver bags contain 5 posh salmon bags, 3 vibrant tomato bags."sv,
        "dotted white bags contain 3 dim fuchsia bags, 4 shiny gold bags, 2 bright olive bags, 4 muted purple bags."sv,
        "faded bronze bags contain 3 pale green bags, 3 light yellow bags, 1 clear teal bag."sv,
        "striped turquoise bags contain 4 mirrored aqua bags, 2 wavy orange bags, 1 pale lavender bag, 4 drab aqua bags."sv,
        "clear lime bags contain 1 plaid green bag, 3 pale gold bags, 2 bright gray bags."sv,
        "drab salmon bags contain 3 dull tomato bags."sv,
        "plaid red bags contain 5 pale brown bags."sv,
        "posh coral bags contain 2 dim violet bags, 4 dotted teal bags, 2 plaid red bags, 4 muted green bags."sv,
        "light bronze bags contain 4 light purple bags."sv,
        "faded orange bags contain 2 light teal bags."sv,
        "dotted lavender bags contain 2 light olive bags, 3 muted tomato bags."sv,
        "bright orange bags contain 3 light gray bags, 4 striped purple bags, 5 dull tomato bags."sv,
        "mirrored coral bags contain 3 faded gray bags, 5 pale green bags, 4 pale aqua bags, 4 muted bronze bags."sv,
        "dull plum bags contain 4 posh crimson bags, 4 clear cyan bags, 4 shiny white bags, 2 dotted maroon bags."sv,
        "shiny blue bags contain 5 dim lime bags, 2 dim gray bags, 5 dark cyan bags, 3 posh teal bags."sv,
        "mirrored fuchsia bags contain 4 muted tomato bags, 5 dotted chartreuse bags, 1 light red bag, 2 bright yellow bags."sv,
        "dotted teal bags contain 1 dotted gray bag, 1 muted brown bag."sv,
        "mirrored tan bags contain 2 clear aqua bags, 4 dim violet bags, 1 wavy gray bag."sv,
        "posh chartreuse bags contain 2 faded blue bags, 4 dark coral bags, 2 light maroon bags, 5 dark purple bags."sv,
        "shiny tan bags contain 1 wavy salmon bag, 2 shiny red bags, 5 clear coral bags, 3 wavy gold bags."sv,
        "vibrant salmon bags contain 3 clear brown bags, 3 pale gold bags, 5 clear blue bags."sv,
        "plaid beige bags contain 5 vibrant lavender bags, 2 dim brown bags, 4 dull yellow bags."sv,
        "muted olive bags contain 3 vibrant blue bags, 5 shiny crimson bags, 5 pale beige bags, 2 dotted chartreuse bags."sv,
        "clear beige bags contain 4 drab coral bags, 4 dark maroon bags, 1 light indigo bag."sv,
        "dull fuchsia bags contain 2 pale magenta bags, 1 dotted indigo bag."sv,
        "dark gold bags contain 3 posh crimson bags, 3 mirrored lavender bags."sv,
        "pale plum bags contain 1 light bronze bag, 5 dotted violet bags, 2 dark salmon bags."sv,
        "drab fuchsia bags contain 4 dull brown bags, 5 muted bronze bags."sv,
        "mirrored black bags contain 1 muted silver bag, 3 plaid gray bags, 4 bright purple bags."sv,
        "posh blue bags contain 3 dull beige bags, 5 dull olive bags."sv,
        "posh beige bags contain 3 vibrant turquoise bags, 3 dotted lime bags."sv,
        "light aqua bags contain 2 mirrored teal bags, 1 vibrant lime bag, 1 dim olive bag."sv,
        "muted tomato bags contain 5 dim lavender bags."sv,
        "dim coral bags contain 4 shiny magenta bags, 4 drab violet bags, 5 clear brown bags."sv,
    };
}
